server {
    listen 80;
    server_name app.your-domain.com;

    root /var/www/akuntansi-bpkad/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
